---
- name: Mark work profile role applied
  ansible.builtin.set_fact:
    workstation_work_role_applied: true

- name: Import vault_tools role
  ansible.builtin.import_role:
    name: vault_tools

- name: Import klam role
  ansible.builtin.import_role:
    name: klam
